language:node_js
node_js:
  _ "stable"
cache:
  directories:
  - node_modules
env:
  - CI=true
script:
    - npm run build-storybook # 默认执行npm test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  # keep_history: true 
  local_dir: storybook-static #默认上传build文件夹
  on:
    branch: main